theme: jekyll-theme-chirpy
baseurl: ""
lang: en
# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone:
title: d3rb1n # the main title
tagline: Bug hunting, CTF's, and all things infosec. # it will display as the sub-title
description: >- # used by seo meta and the atom feed
  Bug hunting, CTF's, and all things infosec.
url: "https://d3rb1n.github.io"
github:
  username: d3rb1n # change to your github username
twitter:
  username: d3rb1n # change to your twitter username
social:
  name: d3rb1n
  email: # change to your email address
  links:
    - https://twitter.com/d3rb1nator # change to your twitter homepage
    - https://github.com/d3rb1n # change to your github homepage
google_site_verification: # fill in to your verification string
theme_mode: dark
img_cdn:
avatar: /assets/img/favicons/favicon-32x32.png
toc: true
pwa:
  enabled: true # the option for PWA feature
paginate: 10


# ------------ The following options are not recommended to be modified ------------------

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tags:
    output: true
  categories:
    output: true
  tabs:
    output: true
    sort_by: order
    panel_includes:
    - toc
  write-ups:
    directory: _write-ups/*/*
    output: true
    sort_by: order
    panel_includes:
    - toc
    extensions: [md, txt, log, hash, png]

search:
  collections:
    - posts
    - pages
    - write-ups
    - tabs


defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: "" # An empty string here means all files in the project
      type: write-ups
    values:
      layout: page
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      output: true
      author: d3rb1n
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true
  - scope:
      type: categories  # select all category pages
    values:
      layout: category_page
      permalink: categories/:category/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

include:
  - _tabs/images/

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

debug: true
